name: Hasaki.vn Automation Regression

on:
  push:
    branches: [develop/github_action]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  E2E_Purchase_Flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
          
                - name: Install Edge
                run: |
                  sudo apt-get update
                  sudo apt-get install -y microsoft-edge-stable

      - name: Run Maven Tests (Headless)
        run: |
          mvn clean test \
          -DsuiteXmlFile=src/test/java/resources/master/Master_E2E_Purchase.xml \
          -Dheadless=true
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-artifacts
          path: |
            target/surefire-reports/
            ScreenShots/
            allure-results/

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages